name: SonarCloud Scan
  uses: SonarSource/sonarcloud-github-action@v1.6
  with:
    # Additional arguments to the sonarcloud scanner
    args: # optional
    # Set the sonar.projectBaseDir analysis property
    projectBaseDir: # optional, default is .
